GreenWiNit/backend

build.gradle, src/main/java/com/example/green/infra/storage/S3StorageHelper.java, src/test/java/com/example/green/domain/TestEntityTest.java, src/test/java/com/example/green/domain/file/utils/ImageValidatorTest.java, src/test/java/com/example/green/dummy/ApiDummyController.java, src/test/java/com/example/green/dummy/ErrorDummyController.java, src/test/java/com/example/green/dummy/ValidationDto.java, src/test/java/com/example/green/global/HealthControllerTest.java, src/test/java/com/example/green/global/api/ApiTest.java, src/test/java/com/example/green/global/error/ExceptionHandlerTest.java, src/test/java/com/example/green/global/error/ValidationExceptionHandlerTest.java, src/test/java/com/example/green/utils/IdUtilsTest.java, src/test/java/com/example/green/utils/TimeUtilsTest.java, src/test/java/com/example/green/utils/UriValidatorTest.java, src/test/java/com/example/integration/common/ServiceIntegrationTest.java, src/test/java/com/example/integration/config/MySqlTestContainerConfig.java, src/test/java/com/example/integration/config/S3TestContainerConfig.java, src/test/java/com/example/integration/file/FileServiceIntTest.java, src/test/java/com/example/integration/file/FileTestUtil.java, src/test/resources/application.yml
close #12 
* test container를 활용해 테스트 환경에서도 product db와 같은 환경에서 테스트를 진행했습니다.
* aws 가상화를 지원하는 Localstack을 활용해 파일 업로드를 확인했습니다.
* 테스트 과정 중 파일 키 추출 로직에 오류가 있어 수정하게 됐습니다.
* 해당 작업으로 인해 로컬 스택을 자세히 학습하게 되었습니다.
* [블로그](https://velog.io/@jihwankim128/LocalStack-S3%EC%9D%98-%EC%88%A8%EA%B2%A8%EC%A7%84-%EB%B9%84%EB%B0%80%EC%9D%84-%ED%8C%8C%ED%97%A4%EC%B9%98%EB%8B%A4) 에 이번 작업을 통해 알게 된 내용을 작성했는데, 좋은 소재가 되었으면 좋겠습니다!
* Jpa Query Method는 이미 추상화가 너무 잘되어있어 굳이 테스트 하지 않았습니다.
> 이미지
>
> ex) 메서드 명칭
- `P2`: …
=> test: [#12] 이미지 업로드 통합 테스트 작업 

.github/workflows/deploy.yaml, .github/workflows/integration-test.yaml, .github/workflows/pr-check.yaml
#16 
-  script를 이해하기 쉽도록 주석 추가
- CD 파일에서 artifact를 복사하기 위한 경로를 읽을 때, ""를 제거
> #### 파일 설명
> pr-check.yaml: PR이 생성되거나 업데이트될 때만 실행 (merge 전)
> integration-test.yaml: PR에 특정 라벨이 있을 때만 실행 (merge 전)
> deploy.yaml: PR이 merge될 때만 실행되며, 이전 워크플로우들의 테스트를 포함
1. PR 생성 및 코드 푸시
a. 기능 개발 후 main 브랜치로 Pull Request를 생성하고 코드를 푸시합니다.
b. 이때 자동으로 pr-check.yaml 워크플로우가 실행되어 **단위 테스트 및 정적 검사(Checkstyle 등)**가 수행됩니다.
2. 동료에게 코드 리뷰 요청
a. PR이 생성되면 팀원들이 코드를 리뷰합니다.
b. 리뷰 도중 문제가 생기면 개발자는 코드를 수정하고 다시 커밋 & 푸시하며, pr-check는 자동 재실행됩니다.
3. 통합 테스트 실행 요청 👀
a. 리뷰가 완료되고 추가 수정이 없으면, PR에 `run-integration-test` 라벨을 추가합니다. -> 개발자가 직접!
b. 이 라벨을 감지한 GitHub Actions가 integration-test.yaml 워크플로우를 실행하여 통합 테스트를 수행합니다.
4. Merge 버튼 활성화
a. pr-check, integration-test 두 테스트가 모두 성공해야 GitHub의 Merge 버튼이 활성화됩니다.
b. 이는 Branch protection rule에서 설정한 필수 …
=> CICD: [#16] cd 파일에서 artifact를 copy할 때의 경로에서 "" 제거

src/main/java/com/example/green/global/error/GlobalExceptionHandler.java, src/main/java/com/example/green/global/error/dto/DetailedExceptionResponse.java, src/main/java/com/example/green/global/error/dto/ErrorSpot.java, src/main/java/com/example/green/global/error/dto/ExceptionResponse.java, src/test/java/com/example/green/global/error/ValidationExceptionHandlerTest.java
close #28 
bean Validation 예외 메세지를 포함하도록 수정
>
> ex) 메서드 명칭
=> refactor:[#28] bean validation 메세지 포함하도록 수정

src/main/java/com/example/green/domain/file/controller/ImageUploadController.java, src/main/java/com/example/green/domain/file/controller/converter/StringToPurposeConverter.java, src/main/java/com/example/green/domain/file/controller/docs/ImageUploadControllerDocs.java, src/main/java/com/example/green/domain/file/controller/message/ImageResponseMessage.java, src/main/java/com/example/green/domain/file/domain/vo/Purpose.java, src/main/java/com/example/green/domain/file/exception/FileExceptionMessage.java, src/main/java/com/example/green/domain/file/service/FileService.java, src/main/java/com/example/green/domain/file/service/StorageHelper.java, src/main/java/com/example/green/infra/storage/S3StorageHelper.java, src/test/java/com/example/green/domain/file/controller/ImageUploadControllerTest.java, src/test/java/com/example/green/domain/file/controller/converter/StringToPurposeConverterTest.java, src/test/java/com/example/green/domain/file/service/FileServiceTest.java, src/test/java/com/example/green/template/base/BaseControllerUnitTest.java, src/test/java/com/example/green/template/request/ImageUploadRequest.java, src/test/java/com/example/integration/file/FileServiceIntTest.java
close #33 
이미지 업로드 통합 controller 제작
service 코드 리팩토링 
> 이미지
>
> ex) 메서드 명칭
=> feat: [#33] 이미지 업로드 컨트롤러 구현 및 리팩터링

src/main/java/com/example/green/domain/info/controller/InfoController.java, src/main/java/com/example/green/domain/info/controller/InfoControllerDocs.java, src/main/java/com/example/green/domain/info/controller/api/InfoResponseMessage.java, src/main/java/com/example/green/domain/info/domain/InfoEntity.java, src/main/java/com/example/green/domain/info/domain/vo/InfoCategory.java, src/main/java/com/example/green/domain/info/dto/InfoListResponse.java, src/main/java/com/example/green/domain/info/dto/InfoRequest.java, src/main/java/com/example/green/domain/info/dto/InfoResponse.java, src/main/java/com/example/green/domain/info/exception/InfoException.java, src/main/java/com/example/green/domain/info/exception/InfoExceptionMessage.java, src/main/java/com/example/green/domain/info/repository/InfoRepository.java, src/main/java/com/example/green/domain/info/service/InfoService.java, src/test/java/com/example/green/domain/info/domain/InfoEntityTest.java
* InfoEntity 도메인 테스트 (InfoRequest DTO 생성)
* InfoEntity 도메인 생성
* 클래스 다이어그램 바탕으로 개괄적인 info context 골격 형성
* file context purpose info enum 추가
> #34 rebase 오류로 새 브랜치 생성, 내용 같음 
- InfoEntity 도메인 테스트 (생성/수정 정도로만)
- InfoEntity 도메인 생성
- 클래스 다이어그램 바탕으로 개괄적인 info context 골격 형성
> 도메인 단위 테스트시 고려한 사항들 
**1. Exception 처리**
- 필드에 대한 유효성 검사는 hanlder에서 핸들러에서 처리
**2. Entity 에 객체 생성 메서드 필요성**
- Entity 생성은 테스트 코드에서나 많이 사용되기 때문에 이너 메서드로 뽑아놓았고, Entity 생성은 DTO 에서 메서드로 구현할 예정
- 따라서 Builder 만 사용하여 생성자 구현하였음
**3. 그렇다면 단순히 상태값 변경 정도면 테스트로 구현함**
- 필드에 대한 유효성 검증은 ExceptionHandler에서 대부분 처리한다. (추후 컨트롤러 슬라이스 테스트에서)
- 카테고리 enum의 request/response는 각각 리포지토리 단위 , 서비스 통합에서 확인한다.
- 권한에 대한 검증은 SpringSecurity Filter에서 공통 에러로 처리한다. (관리자 권한)
> 이미지
- commit message에 이전에 지웠던 feat 번호를 잘 못 작성했어요!  ㅠ …
=> feat: [#39] 정보 도메인 단위테스트 및 구현체 생성

.github/workflows/deploy.yaml
closed #41 
- 배포 설정 업데이트
- 배포 시, swagger 경로 추가 (프론트와 같이 써야 해서 /api 사용) 
=> cicd: [#41] Swagger 경로 환경 변수 추가 

.github/workflows/deploy.yaml
#41 
- .env 파일을 따로 copy 하도록 수정
>
> ex) 메서드 명칭
=> cicd: [#41] .env 파일 따로 copy 하도록 변경

src/main/java/com/example/green/domain/common/TimeBaseEntity.java, src/main/java/com/example/green/domain/pointshop/entity/delivery/DeliveryAddress.java, src/main/java/com/example/green/domain/pointshop/entity/delivery/vo/Address.java, src/main/java/com/example/green/domain/pointshop/entity/delivery/vo/Recipient.java, src/main/java/com/example/green/domain/pointshop/exception/deliveryaddress/DeliveryAddressException.java, src/main/java/com/example/green/domain/pointshop/exception/deliveryaddress/DeliveryAddressExceptionMessage.java, src/test/java/com/example/green/domain/pointshop/entity/delivery/DeliveryAddressTest.java, src/test/java/com/example/green/domain/pointshop/entity/delivery/vo/AddressTest.java, src/test/java/com/example/green/domain/pointshop/entity/delivery/vo/RecipientTest.java
close #54 
> 이미지
>
> ex) 메서드 명칭
=> feat:[#54] 배송지 엔터티 구현

src/main/java/com/example/green/domain/pointshop/controller/DeliveryAddressController.java, src/main/java/com/example/green/domain/pointshop/controller/docs/DeliveryAddressControllerDocs.java, src/main/java/com/example/green/domain/pointshop/controller/dto/DeliveryAddressCreateDto.java, src/main/java/com/example/green/domain/pointshop/controller/message/DeliveryAddressResponseMessage.java, src/main/java/com/example/green/domain/pointshop/entity/delivery/DeliveryAddress.java, src/main/java/com/example/green/domain/pointshop/entity/delivery/vo/Recipient.java, src/main/java/com/example/green/domain/pointshop/exception/deliveryaddress/DeliveryAddressExceptionMessage.java, src/main/java/com/example/green/domain/pointshop/repository/DeliveryAddressRepository.java, src/main/java/com/example/green/domain/pointshop/service/DeliveryAddressService.java, src/main/java/com/example/green/domain/pointshop/service/command/DeliveryAddressCreateCommand.java, src/main/java/com/example/green/domain/pointshop/service/result/DeliveryResult.java, src/test/java/com/example/green/domain/pointshop/controller/DeliveryAddressControllerTest.java, src/test/java/com/example/green/domain/pointshop/controller/request/DeliveryAddressRequest.java, src/test/java/com/example/green/domain/pointshop/entity/delivery/DeliveryAddressTest.java, src/test/java/com/example/green/domain/pointshop/entity/delivery/vo/RecipientTest.java, src/test/java/com/example/green/domain/pointshop/service/DeliveryAddressServiceTest.java
close #75 
기본 정보만 작업
나중에 Security 설정에 따른 수정
휴대폰 인증 추가 예정
> 이미지
>
> ex) 메서드 명칭
=> feat: [#75] 배송지 관련 작업

src/main/java/com/example/green/domain/info/controller/InfoController.java, src/main/java/com/example/green/domain/info/controller/InfoControllerDocs.java, src/main/java/com/example/green/domain/info/controller/api/InfoResponseMessage.java, src/main/java/com/example/green/domain/info/domain/vo/InfoCategory.java, src/main/java/com/example/green/domain/info/dto/InfoPage.java, src/main/java/com/example/green/domain/info/dto/InfoRequest.java, src/main/java/com/example/green/domain/info/dto/admin/InfoDetailResponseByAdmin.java, src/main/java/com/example/green/domain/info/dto/admin/InfoSearchListResponseByAdmin.java, src/main/java/com/example/green/domain/info/dto/admin/InfoSearchResponseByAdmin.java, src/main/java/com/example/green/domain/info/dto/user/InfoDetailResponseByUser.java, src/main/java/com/example/green/domain/info/dto/user/InfoSearchListResponseByUser.java, src/main/java/com/example/green/domain/info/dto/user/InfoSearchResponseByUser.java, src/main/java/com/example/green/domain/info/service/InfoService.java, src/main/java/com/example/green/domain/info/service/InfoServiceImpl.java, src/test/java/com/example/green/domain/info/controller/InfoControllerTest.java, src/test/java/com/example/green/domain/info/domain/InfoEntityTest.java, src/test/java/com/example/integration/info/InfoServiceIntTest.java
> ✅ **요청값**과 **그에 따른 공통 응답 API** 위주로한 단위 테스트 
**[컨트롤러 단위]**
* @RequestBody에러 (Enum 필드 매핑) 및 @Validation 체크 (ArgumentType)
* Test 작성하며 Controller/ResponseMessage 및 swagger 구현
**[도메인 단위 추가]**
* ENUM 값 Entity 도메인단 검증 (Jackson 에러 확인)
**[swagger]**
* swagger 적용하여 로컬 확인 
> 이미지
>
> ex) 메서드 명칭
=> feat: [#65] 컨트롤러 슬라이스 단위 테스트 

src/main/java/com/example/green/domain/pointshop/controller/PointProductAdminController.java, src/main/java/com/example/green/domain/pointshop/controller/PointProductController.java, src/main/java/com/example/green/domain/pointshop/controller/docs/PointProductAdminControllerDocs.java, src/main/java/com/example/green/domain/pointshop/controller/docs/PointProductControllerDocs.java, src/main/java/com/example/green/domain/pointshop/controller/dto/PointProductDetail.java, src/main/java/com/example/green/domain/pointshop/controller/dto/PointProductView.java, src/main/java/com/example/green/domain/pointshop/controller/dto/PointProductsView.java, src/main/java/com/example/green/domain/pointshop/controller/message/PointProductResponseMessage.java, src/main/java/com/example/green/domain/pointshop/controller/query/PointProductQueryRepository.java, src/main/java/com/example/green/infra/query/pointproduct/PointProductPredicates.java, src/main/java/com/example/green/infra/query/pointproduct/PointProductProjections.java, src/main/java/com/example/green/infra/query/pointproduct/PointProductQueryExecutor.java, src/main/java/com/example/green/infra/query/pointproduct/PointProductQueryRepositoryImpl.java, src/test/java/com/example/green/domain/pointshop/controller/PointProductAdminControllerTest.java, src/test/java/com/example/green/domain/pointshop/controller/PointProductControllerTest.java, src/test/java/com/example/green/domain/pointshop/controller/request/PointProductRequest.java
close #72 
> 이미지
>
> ex) 메서드 명칭
=> feat: [#72] 포인트 상점 이용자 쿼리 기능 구현

src/main/java/com/example/green/domain/pointshop/controller/DeliveryAddressController.java, src/main/java/com/example/green/domain/pointshop/controller/OrderController.java, src/main/java/com/example/green/domain/pointshop/controller/dto/SingleOrderRequest.java, src/main/java/com/example/green/domain/pointshop/controller/message/OrderResponseMessage.java, src/main/java/com/example/green/domain/pointshop/entity/order/Order.java, src/main/java/com/example/green/domain/pointshop/entity/order/vo/ItemSnapshot.java, src/main/java/com/example/green/domain/pointshop/entity/point/vo/PointAmount.java, src/main/java/com/example/green/domain/pointshop/exception/deliveryaddress/DeliveryAddressExceptionMessage.java, src/main/java/com/example/green/domain/pointshop/exception/point/PointExceptionMessage.java, src/main/java/com/example/green/domain/pointshop/repository/DeliveryAddressRepository.java, src/main/java/com/example/green/domain/pointshop/repository/OrderRepository.java, src/main/java/com/example/green/domain/pointshop/repository/PointTransactionRepository.java, src/main/java/com/example/green/domain/pointshop/service/DeliveryAddressService.java, src/main/java/com/example/green/domain/pointshop/service/OrderService.java, src/main/java/com/example/green/domain/pointshop/service/PointProductService.java, src/main/java/com/example/green/domain/pointshop/service/PointTransactionService.java, src/main/java/com/example/green/domain/pointshop/service/command/SingleOrderCommand.java, src/test/java/com/example/green/domain/pointshop/controller/DeliveryAddressControllerTest.java, src/test/java/com/example/green/domain/pointshop/controller/OrderControllerTest.java, src/test/java/com/example/green/domain/pointshop/entity/order/OrderItemTest.java, src/test/java/com/example/green/domain/pointshop/entity/order/OrderTest.java, src/test/java/com/example/green/domain/pointshop/service/DeliveryAddressServiceTest.java, src/test/java/com/example/green/domain/pointshop/service/OrderServiceTest.java, src/test/java/com/example/green/domain/pointshop/service/PointProductServiceTest.java
포인트 상품 주문 기능
> 이미지
>
> ex) 메서드 명칭
=> feat: 포인트 상품 주문 기능 구현 (#83)

src/main/java/com/example/green/domain/pointshop/controller/OrderController.java, src/main/java/com/example/green/domain/pointshop/controller/docs/OrderControllerDocs.java, src/main/java/com/example/green/domain/pointshop/controller/dto/SingleOrderRequest.java, src/main/java/com/example/green/domain/pointshop/exception/OrderExceptionMessage.java, src/test/java/com/example/green/domain/pointshop/controller/OrderControllerTest.java
=> docs: 상품 주문 스웨거 문서화 추가 (#83)

src/main/java/com/example/green/domain/challenge/client/PointEarnClient.java, src/main/java/com/example/green/domain/challenge/client/request/PointEarnRequest.java, src/main/java/com/example/green/domain/member/client/PointEarnClient.java, src/main/java/com/example/green/domain/point/adapter/PointTransactionAdaptor.java, src/main/java/com/example/green/domain/point/entity/vo/PointAmount.java, src/main/java/com/example/green/domain/point/service/PointTransactionService.java, src/test/java/com/example/green/domain/point/adapter/PointTransactionAdaptorTest.java, src/test/java/com/example/green/domain/point/service/PointTransactionServiceTest.java
=> feat: [#83] 다른 컨텍스트 포인트 지급 어댑터 구현

src/main/java/com/example/green/domain/point/controller/PointTransactionController.java, src/main/java/com/example/green/domain/point/controller/docs/PointTransactionControllerDocs.java, src/main/java/com/example/green/domain/point/controller/dto/MemberPointSummary.java, src/main/java/com/example/green/domain/point/controller/dto/MyPointTransaction.java, src/main/java/com/example/green/domain/point/controller/message/PointTransactionResponseMessage.java, src/main/java/com/example/green/domain/point/controller/query/PointTransactionQueryRepository.java, src/main/java/com/example/green/domain/point/repository/PointTransactionRepository.java, src/main/java/com/example/green/domain/point/service/PointTransactionService.java, src/main/java/com/example/green/domain/pointshop/controller/PointProductController.java, src/main/java/com/example/green/domain/pointshop/service/PointProductDomainService.java, src/main/java/com/example/green/global/api/page/CursorTemplate.java, src/main/java/com/example/green/infra/query/point/PointTransactionQueryImpl.java, src/main/java/com/example/green/infra/query/pointproduct/PointProductQueryRepositoryImpl.java, src/test/java/com/example/green/domain/point/controller/PointTransactionControllerTest.java, src/test/java/com/example/green/global/api/page/CursorTemplateTest.java
=> feat: [#83] 사용자 포인트 조회 기능

src/main/java/com/example/green/domain/challenge/client/request/PointEarnRequest.java, src/main/java/com/example/green/domain/member/client/PointClient.java, src/main/java/com/example/green/domain/point/adapter/PointTransactionAdaptor.java, src/main/java/com/example/green/domain/point/controller/PointTransactionAdminController.java, src/main/java/com/example/green/domain/point/controller/PointTransactionController.java, src/main/java/com/example/green/domain/point/controller/docs/PointTransactionAdminControllerDocs.java, src/main/java/com/example/green/domain/point/controller/docs/PointTransactionControllerDocs.java, src/main/java/com/example/green/domain/point/controller/dto/PointTransactionSearchCondition.java, src/main/java/com/example/green/domain/point/controller/mapper/PointTransactionExcelMapper.java, src/main/java/com/example/green/domain/point/entity/vo/PointSource.java, src/main/java/com/example/green/domain/point/entity/vo/TargetType.java, src/main/java/com/example/green/domain/point/repository/PointTransactionQueryRepository.java, src/main/java/com/example/green/domain/point/repository/dto/MemberPointSummary.java, src/main/java/com/example/green/domain/point/repository/dto/MyPointTransaction.java, src/main/java/com/example/green/domain/point/repository/dto/MyPointTransactionDto.java, src/main/java/com/example/green/domain/point/repository/dto/PointTransactionDto.java, src/main/java/com/example/green/domain/pointshop/client/dto/PointSpendRequest.java, src/main/java/com/example/green/infra/query/point/PointTransactionPredicates.java, src/main/java/com/example/green/infra/query/point/PointTransactionProjections.java, src/main/java/com/example/green/infra/query/point/PointTransactionQueryExecutor.java, src/main/java/com/example/green/infra/query/point/PointTransactionQueryImpl.java, src/test/java/com/example/green/domain/point/adapter/PointTransactionAdaptorTest.java, src/test/java/com/example/green/domain/point/controller/PointTransactionControllerTest.java
=> feat: [#83] 관리자 포인트 조회 기능 구현

src/main/java/com/example/green/global/config/SecurityConfig.java, src/main/resources/application.yml, src/test/java/com/example/integration/security/SecurityAnnotationTest.java, src/test/resources/application.yml
#108 
- application.yaml에 백엔드 url 추가
- cors 설정에 백엔드 url 추가
빠른 오류 수정을 위해 바로 merge 하겠습니다.
@yunjeooong cors를 수정하게 되는 부분이 있어서 윤정님이 한 번 확인만 해주시면 감사하겠습니다!
=> fix: [#108] 백엔드 URL 설정 추가 및 CORS 허용 출처 확장

src/main/java/com/example/green/global/config/OpenApiConfig.java, src/main/java/com/example/green/global/config/SecurityConfig.java
#108 
- Swagger 설정에 백엔드 서버 URL 정확히 설정
- cors에 사용되는 methods, headers 정확히 설정 -> `*` 인식을 못하는 경우 많음.
=> fix: Swagger 설정에 백엔드 서버 URL 정확히 설정 및 로깅 기능 구현

src/main/java/com/example/green/domain/mypage/client/PointTotalGetClient.java, src/main/java/com/example/green/domain/mypage/service/MypageFacadeService.java, src/main/java/com/example/green/domain/point/adapter/PointTransactionAdaptor.java, src/main/resources/application-mail.yml, src/test/java/com/example/green/domain/point/adapter/PointTransactionAdaptorTest.java
close #114 
> 이미지
>
> ex) 메서드 명칭
=> feat: 회원 포인트 조회 어댑터 구현(#114)

src/main/resources/application-mail.yml
=> fix: yml 오타 수정

src/main/java/com/example/green/domain/mypage/controller/MypageController.java, src/main/java/com/example/green/domain/mypage/controller/MypageControllerDocs.java, src/main/java/com/example/green/domain/mypage/dto/MypageMainResponseDto.java, src/main/java/com/example/green/domain/mypage/exception/MypageException.java, src/main/java/com/example/green/domain/mypage/exception/MypageExceptionMessage.java, src/main/java/com/example/green/domain/mypage/service/MypageFacadeService.java, src/test/java/com/example/green/domain/mypage/service/MypageFacadeServiceTest.java
> 더미로 잡아둔 값들을 수정 
* 포인트에 따른 레벨 계산
* DTO 레벨 필드 추가
* 레벨 계산 메서드 추가
* Exception Message 작성
* 메인 조회 단위 테스트
* DTO/Controller docs 작성
* memberId 로 변수명 변경
> 이미지
>
> ex) 메서드 명칭
=> refactor : [#107] 마이페이지 메인 조회 리팩토링

src/main/java/com/example/green/domain/pointshop/client/PhoneVerificationClient.java, src/main/java/com/example/green/domain/pointshop/controller/DeliveryAddressController.java, src/main/java/com/example/green/domain/pointshop/controller/docs/DeliveryAddressControllerDocs.java, src/main/java/com/example/green/domain/pointshop/controller/dto/DeliveryAddressUpdateDto.java, src/main/java/com/example/green/domain/pointshop/controller/message/DeliveryAddressResponseMessage.java, src/main/java/com/example/green/domain/pointshop/entity/delivery/DeliveryAddress.java, src/main/java/com/example/green/domain/pointshop/service/DeliveryAddressService.java, src/main/java/com/example/green/domain/pointshop/service/command/DeliveryAddressUpdateCommand.java, src/test/java/com/example/green/domain/pointshop/controller/DeliveryAddressControllerTest.java, src/test/java/com/example/green/domain/pointshop/controller/request/DeliveryAddressRequest.java, src/test/java/com/example/green/domain/pointshop/service/DeliveryAddressServiceTest.java
close #133 
> 이미지
>
> ex) 메서드 명칭
=> feat: [#133] 배송지 관련 기획 측 의견 반영 Story Book 참고

src/main/java/com/example/green/domain/info/dto/user/InfoSearchResponseByUser.java, src/main/java/com/example/green/domain/mypage/controller/MypageControllerDocs.java
* 사용자단 정보조회 정보내용 추가함
* 마이페이지 수정
> 이미지
>
> ex) 메서드 명칭
=> chore : [#104] 사용자단 정보공유 수정

src/main/java/com/example/green/domain/info/dto/user/InfoDetailResponseByUser.java, src/test/java/com/example/green/domain/info/controller/InfoControllerTest.java
> * 이미지 경로 추가
> 이미지
>
> ex) 메서드 명칭
=> chore : [#148]사용자 정보조회 상세 이미지 경로 추가

src/main/java/com/example/green/domain/challenge/controller/TeamChallengeGroupController.java, src/main/java/com/example/green/domain/challenge/controller/docs/TeamChallengeGroupControllerDocs.java, src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupCreateRequestDto.java, src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupDetailResponseDto.java, src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupListResponseDto.java, src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupUpdateRequestDto.java, src/main/java/com/example/green/domain/challenge/controller/message/TeamChallengeGroupResponseMessage.java, src/main/java/com/example/green/domain/challenge/entity/TeamChallengeGroup.java, src/main/java/com/example/green/domain/challenge/entity/vo/GroupAddress.java, src/main/java/com/example/green/domain/challenge/exception/ChallengeExceptionMessage.java, src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepository.java, src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepositoryCustom.java, src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepositoryImpl.java, src/main/java/com/example/green/domain/challenge/service/TeamChallengeGroupService.java, src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeGroupParticipationRepository.java, src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeParticipationRepository.java, src/test/java/com/example/green/domain/challenge/controller/TeamChallengeGroupControllerTest.java, src/test/java/com/example/green/domain/challenge/entity/TeamChallengeGroupTest.java, src/test/java/com/example/green/domain/challenge/entity/TeamChallengeTest.java, src/test/java/com/example/green/domain/challenge/entity/vo/GroupAddressTest.java, src/test/java/com/example/green/domain/challenge/service/ChallengeServiceTest.java, src/test/java/com/example/green/domain/challenge/service/TeamChallengeGroupServiceTest.java, src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeCertificationTest.java, src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeGroupParticipationTest.java, src/test/java/com/example/integration/challenge/TeamChallengeGroupRepositoryTest.java
closed #143
- 그룹 관련 API 구현
- 생성 : 자동 리더 할당
- 수정, 삭제 : 리더만 가능
- 조회 : 팀 챌린지에 가입한 사람만 조회 가능
> 이미지
>
> ex) 메서드 명칭
=> feat: [#143] 팀챌린지 - 팀(그룹) 생성/수정/삭제/조회 및 참여

src/main/java/com/example/green/domain/challengecert/controller/ChallengeCertificationController.java, src/main/java/com/example/green/domain/challengecert/controller/docs/ChallengeCertificationControllerDocs.java, src/main/java/com/example/green/domain/challengecert/controller/message/ChallengeCertificationResponseMessage.java, src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateRequestDto.java, src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateResponseDto.java, src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationDetailResponseDto.java, src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationListResponseDto.java, src/main/java/com/example/green/domain/challengecert/entity/BaseChallengeCertification.java, src/main/java/com/example/green/domain/challengecert/entity/PersonalChallengeCertification.java, src/main/java/com/example/green/domain/challengecert/entity/PersonalChallengeParticipation.java, src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeCertification.java, src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeGroupParticipation.java, src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeParticipation.java, src/main/java/com/example/green/domain/challengecert/exception/ChallengeCertExceptionMessage.java, src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepository.java, src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepositoryCustom.java, src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepositoryImpl.java, src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepository.java, src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepositoryCustom.java, src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepositoryImpl.java, src/main/java/com/example/green/domain/challengecert/service/ChallengeCertificationService.java, src/main/java/com/example/green/domain/file/domain/vo/Purpose.java, src/test/java/com/example/green/domain/challengecert/controller/ChallengeCertificationControllerTest.java, src/test/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateRequestDtoTest.java, src/test/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateResponseDtoTest.java, src/test/java/com/example/green/domain/challengecert/entity/PersonalChallengeCertificationTest.java, src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeCertificationTest.java, src/test/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepositoryImplTest.java, src/test/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepositoryImplTest.java, src/test/java/com/example/green/domain/challengecert/service/ChallengeCertificationServiceTest.java
closed #147 
- 챌린지 인증 API 구현
- 챌린지 인증 조회 (팀/개인 목록, 상세 조회) API 구현
> 이미지
>
> ex) 메서드 명칭
=> feat: [#147] 챌린지 인증 - 회원용

src/main/java/com/example/green/global/config/SecurityConfig.java
- greenwinit.pages.dev 및 하위 도메인 추가
- greenwinit-admin-panel.pages.dev 및 하위 도메인 추가
- internal-a-panel.greenwinit.store 추가
- 와일드카드 패턴은 setAllowedOriginPatterns로 분리
- 모든 origin에 HTTPS 프로토콜 명시
추가된 도메인:
- https://greenwinit.pages.dev
- https://*.greenwinit.pages.dev
- https://greenwinit-admin-panel.pages.dev
- https://*.greenwinit-admin-panel.pages.dev
- https://internal-a-panel.greenwinit.store
https://github.com/GreenWiNit/backend/issues/144
> 이미지
>
> ex) 메서드 명칭
- `P2`: 반영을 고려해 주세요 …
=> [hotfix] feat: CORS 설정에 Cloudflare Pages 및 관리자 패널 도메인 추가

src/main/java/com/example/green/domain/auth/CustomSuccessHandler.java
https://github.com/GreenWiNit/backend/issues/154
OAuth2 로그인 후 리다이렉트 URL을 동적으로 결정하도록 개선했습니다.
**문제 상황**
기존에는 application.yml의 app.frontend.base-url이 하드코딩되어 있어 항상 운영 서버(https://www.greenwinit.store)로 리다이렉트됨
로컬 개발환경(localhost:5173/5174) 또는 스테이징 환경(greenwinit.pages.dev)에서 테스트 시에도 운영 서버로 이동되어 테스트 불가
**해결 방안**
getSafeRedirectBase() 메서드 추가: HTTP 요청의 Origin 또는 Referer 헤더를 확인하여 허용된 도메인에서 온 요청인지 검증
허용된 도메인 목록: localhost:3000/5173/5174, greenwinit.pages.dev, www.greenwinit.store
요청이 온 환경으로 다시 리다이렉트되도록 동적 URL 생성
> 이미지
>
> ex) 메서드 명칭
- `P1`: 꼭 …
=> refactor(auth): OAuth2 리다이렉트 URL 처리 방식 개선

src/main/java/com/example/green/domain/auth/CustomSuccessHandler.java, src/main/java/com/example/green/domain/auth/OAuth2FailureHandler.java, src/main/java/com/example/green/domain/auth/OAuth2RedirectValidator.java, src/main/java/com/example/green/global/config/AllowedDomainsPolicy.java, src/main/java/com/example/green/global/config/SecurityConfig.java, src/main/resources/application.yml
문제 해결
- OAuth2 로그인 시 c1637672.greenwinit.pages.dev 등 서브도메인에서 400 Bad Request 에러 발생
- authorization_request_not_found 에러로 인한 cross-domain 세션 유실 문제
주요 변경사항
- AllowedDomainsPolicy: 도메인 정책 중앙 관리 클래스 신규 추가
- 정적 도메인 목록 + 환경변수 도메인 + 와일드카드 패턴 지원
- *.greenwinit.pages.dev 패턴 매칭으로 모든 서브도메인 허용
- OAuth2RedirectValidator: OAuth2 리다이렉트 보안 검증 전용 서비스
- Origin/Referer 헤더 기반 안전한 리다이렉트 URL 검증
- AllowedDomainsPolicy와 연동하여 일관된 도메인 정책 적용
- SecurityConfig: Spring Security 설정 책임만 유지
- 도메인 정책 관련 static 상수 제거 및 AllowedDomainsPolicy 의존성 주입
- CORS 설정과 OAuth2 검증 로직 간 도메인 정책 일치 보장
> 이미지
>
> ex) 메서드 명칭
- 리뷰는 Reviewer로 지정된 시점 기준으로 **3일 이내**에 진행해 …
=> feat: OAuth2 cross-domain 로그인 지원 및 도메인 정책 리팩토링

src/main/java/com/example/green/domain/auth/repository/RefreshTokenRepository.java
=> fix: add missing LIMIT clause

src/main/java/com/example/green/domain/certification/ui/CertificationResponseMessage.java, src/main/java/com/example/green/domain/certification/ui/docs/AdminChallengeCertificationControllerDocs.java, src/main/java/com/example/green/domain/certification/ui/dto/CertificationIdentifierDto.java
=> docs: 챌린지 인증 스웨거 문서화 추가

src/main/java/com/example/green/domain/challenge/service/ChallengeGroupService.java, src/main/resources/application.yml
=> fix: jpa time zone 설정 수정

src/main/java/com/example/green/domain/certification/domain/ChallengeCertification.java, src/main/resources/application.yml
=> fix: logging 강화

src/main/resources/application.yml
=> fix: korea time 설정 빼먹음

src/main/java/com/example/green/domain/challenge/controller/query/dto/challenge/ChallengeDto.java, src/main/java/com/example/green/domain/challenge/infra/querydsl/PersonalChallengeQueryImpl.java, src/main/java/com/example/green/domain/challenge/infra/querydsl/TeamChallengeQueryImpl.java, src/main/java/com/example/green/domain/challenge/infra/querydsl/executor/PersonalChallengeQueryExecutor.java, src/main/java/com/example/green/domain/challenge/infra/querydsl/projections/PersonalChallengeProjections.java, src/main/java/com/example/green/domain/challenge/infra/querydsl/projections/TeamChallengeProjections.java
=> fix: 조회 시 생성자 매핑 오류 해결

src/main/java/com/example/green/domain/pointshop/product/infra/PointProductPredicates.java, src/main/java/com/example/green/domain/pointshop/product/infra/PointProductQueryRepositoryImpl.java
=> fix: 포인트 상품 목록 display 버그 해결

src/main/java/com/example/green/domain/auth/CustomSuccessHandler.java
=> feat: set domainHost "localhost" if redirectBase isLocalhost

src/main/java/com/example/green/domain/auth/utils/WebUtils.java
=> feat: set domain include localhost

src/main/java/com/example/green/domain/auth/CustomSuccessHandler.java, src/main/java/com/example/green/domain/auth/utils/WebUtils.java
=> feat: pass refresh token if localhost

src/main/java/com/example/green/global/config/AllowedDomainsPolicy.java
=> [Feat] #340 allow cors url, pattern

src/main/resources/application.yml, src/test/resources/application.yml
=> fix: Select rds naming convention
